name: alaa_accounts
description: "حسابات علاء أبو شادي - تجارة الغلال والمحاصيل"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  supabase_flutter: ^2.3.4
  connectivity_plus: any
  uuid: ^4.3.3
  intl: any
  crypto: ^3.0.3
  # حزم استخراج وطباعة الـ PDF:
  pdf: ^3.10.8
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
